/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StickyContainer {
    }
}
declare global {
    interface HTMLStickyContainerElement extends Components.StickyContainer, HTMLStencilElement {
    }
    var HTMLStickyContainerElement: {
        prototype: HTMLStickyContainerElement;
        new (): HTMLStickyContainerElement;
    };
    interface HTMLElementTagNameMap {
        "sticky-container": HTMLStickyContainerElement;
    }
}
declare namespace LocalJSX {
    interface StickyContainer {
    }
    interface IntrinsicElements {
        "sticky-container": StickyContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sticky-container": LocalJSX.StickyContainer & JSXBase.HTMLAttributes<HTMLStickyContainerElement>;
        }
    }
}
